// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izvqijnaakgdmbaidozk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6dnFpam5hYWtnZG1iYWlkb3prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzEyNjIsImV4cCI6MjA2NDUwNzI2Mn0.SDi8uJLj-073Ulc9cXSMCU3-8JxZ87VooSHtKVkADzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);